//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nightingale
{
    using System;
    using System.Collections.Generic;
    
    public partial class Favourite
    {
        public int SessionID { get; set; }
        public string Title { get; set; }
        public string Category { get; set; }
    }
}
